-- Attendance AI v2 - full Excel-style data model
create extension if not exists pgcrypto;

create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  student_id text unique not null,
  name text not null,
  batch text not null check (batch in ('BCS 2A','BCS 2B','BCS 2C','BCS 2D')),
  slr integer,
  code text not null,
  created_at timestamptz default now()
);
create unique index if not exists students_batch_code_uidx on public.students(batch, code);

create table if not exists public.attendance (
  id uuid primary key default gen_random_uuid(),
  student_id text not null references public.students(student_id) on delete cascade,
  batch text not null check (batch in ('BCS 2A','BCS 2B','BCS 2C','BCS 2D')),
  date date not null,
  status text not null default 'P' check(status in ('P','A')),
  source_name text,
  raw_text text,
  created_at timestamptz default now(),
  unique(student_id,date)
);
create index if not exists attendance_batch_date_idx on public.attendance(batch,date);

create table if not exists public.mark_records (
  id uuid primary key default gen_random_uuid(),
  student_id text not null references public.students(student_id) on delete cascade,
  batch text not null check (batch in ('BCS 2A','BCS 2B','BCS 2C','BCS 2D')),
  assessment_values jsonb not null default '{}'::jsonb,
  lia10 jsonb not null default '[]'::jsonb,
  lia16 jsonb not null default '[]'::jsonb,
  lab numeric,
  viva numeric,
  total numeric,
  extra jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now(),
  unique(student_id)
);

create table if not exists public.workbook_meta (
  id bigint generated by default as identity primary key,
  batch text unique not null,
  attendance_headers jsonb not null default '[]'::jsonb,
  mark_headers jsonb not null default '[]'::jsonb,
  updated_at timestamptz default now()
);

alter table public.students enable row level security;
alter table public.attendance enable row level security;
alter table public.mark_records enable row level security;
alter table public.workbook_meta enable row level security;

drop policy if exists "authenticated students" on public.students;
drop policy if exists "authenticated attendance" on public.attendance;
drop policy if exists "authenticated marks" on public.mark_records;
drop policy if exists "authenticated workbook meta" on public.workbook_meta;

create policy "authenticated students" on public.students for all to authenticated using (true) with check (true);
create policy "authenticated attendance" on public.attendance for all to authenticated using (true) with check (true);
create policy "authenticated marks" on public.mark_records for all to authenticated using (true) with check (true);
create policy "authenticated workbook meta" on public.workbook_meta for all to authenticated using (true) with check (true);
